### ISSUE TITLE
All dates/times are NaN

### ISSUE THREAD

**Issue by spilth** [ejschmitt/delayed_job_web#13]
I'm using delayed_job_web for project using Rails 3.0.1 and:

```
delayed_job (3.0.1)
  activesupport (~> 3.0)
delayed_job_active_record (0.3.2)
  activerecord (> 2.1.0)
  delayed_job (~> 3.0.0)
delayed_job_web (1.1.1)
  activerecord (> 3.0.0)
  delayed_job (> 2.0.3)
  haml (~> 3.1.3)
  rdoc
  sinatra (>= 0.9.2)
```

In the delayed_job_web UI, any dates show up as "NaN days ago".

I thought this maybe because I am setting a default time format, but removing it doesn't seem to make a difference:

```
en:
  hello: "Hello world"
  time:
    formats:
      full: "%a, %b %-d, %H:%M %Z"
      default: "%a, %b %-d, %H:%M %Z"
```

I do see valid dates in the delayed_job table for these jobs.
